[package]
name = "solana-nft-minter"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.7.11"
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }
borsh = "0.7.0"


[lib]
crate-type = ["cdylib", "lib"]